language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build  -t cpansegrouw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpansegrouw/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-1"
  env: "DockerReact1-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-126349880551"
  bucket_path: "docker-react-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



