language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build  -t cpansegrouw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpansegrouw/docker-react npm run test